sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
install:
  - pip install coveralls
  - LC_ALL=C pip install .
script:
  - make check
  - coverage run setup.py test
  - coverage report --fail-under=90
after_success:
  - coveralls
branches:
  except:
    - /^[0-9]/
